### ISSUE TITLE
investigate using @babel/preset-env@7.4

### ISSUE THREAD

**Issue by andreineculau** [tobiipro/babel-preset-firecloud#14]
test by building schemata-firecloud, which with `@babel/preset-env@7.4.1` fails with 

```
09:32:23 [INFO] Generating dts/atex-beacon-in-view-event-v1-json.d.ts...
error SyntaxError: Unexpected token W in JSON at position 1
    at JSON.parse (<anonymous>)
    at /Users/andrei/git/firecloud/schemata-firecloud/node_modules/json-schema-to-typescript/dist/src/cli.js:70:33
    at step (/Users/andrei/git/firecloud/schemata-firecloud/node_modules/json-schema-to-typescript/dist/src/cli.js:33:23)
    at Object.next (/Users/andrei/git/firecloud/schemata-firecloud/node_modules/json-schema-to-typescript/dist/src/cli.js:14:53)
    at fulfilled (/Users/andrei/git/firecloud/schemata-firecloud/node_modules/json-schema-to-typescript/dist/src/cli.js:5:58)
```

**Comment by andreineculau** [comment]
upstream issue: https://github.com/babel/babel/issues/9977
